import { BarChart3, MapPinned } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";

import Navbar from "../../components/layout/Navbar";
import { humanize, type Facility, type ThermalEvent } from "../../types/thermal";

const API_BASE_URL = "http://127.0.0.1:8000";

export default function ChartsPage() {
  const { regionId = "dahej", facilityId } = useParams();
  const [facilities, setFacilities] = useState<Facility[]>([]);
  const [events, setEvents] = useState<ThermalEvent[]>([]);
  useEffect(() => { Promise.all([fetch(`${API_BASE_URL}/facilities`).then((response) => response.json()), fetch(`${API_BASE_URL}/map/events?window_id=window-1`).then((response) => response.json())]).then(([facilityData, eventData]) => { setFacilities(facilityData.facilities ?? []); setEvents(eventData.events ?? []); }); }, []);
  const selected = facilities.find((facility) => facility.facility_id === facilityId) ?? facilities[0];
  const facilityEvents = useMemo(() => selected ? events.filter((event) => event.facility_id === selected.facility_id) : [], [events, selected]);
  const max = Math.max(1, ...facilityEvents.map((event) => event.max_frp ?? 0), ...facilityEvents.map((event) => event.baseline_frp ?? 0));
  return <main className="min-h-screen bg-background text-foreground"><Navbar showRegionNav regionName={regionId.toUpperCase()} /><section className="mx-auto max-w-6xl px-4 py-6 md:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[0.16em] text-primary">CHART VIEW</p><h1 className="mt-2 text-2xl font-bold">Facility activity comparison</h1><p className="mt-1 text-sm text-muted-foreground">Observed event FRP compared with the facility baseline in the active replay window.</p></div><Link to={`/region/${regionId}/explore`} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-bold text-slate-700 hover:bg-slate-50"><MapPinned className="h-4 w-4" />Back to map</Link></div><div className="mt-6 grid gap-5 lg:grid-cols-[280px_1fr]"><aside className="rounded-2xl border border-border bg-card p-3">{facilities.map((facility) => <Link key={facility.facility_id} to={`/region/${regionId}/charts/${facility.facility_id}`} className={`block rounded-xl px-3 py-3 text-sm ${selected?.facility_id === facility.facility_id ? "bg-orange-50 font-bold text-orange-800" : "text-slate-600 hover:bg-slate-50"}`}>{facility.name}<span className="mt-0.5 block text-xs font-normal text-slate-400">{humanize(facility.facility_type)}</span></Link>)}</aside><section className="rounded-2xl border border-border bg-card p-5 md:p-6">{!selected ? <p className="text-sm text-slate-500">Loading facility data...</p> : <><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-orange-500" /><div><h2 className="font-bold text-slate-900">{selected.name}</h2><p className="text-xs text-slate-500">{facilityEvents.length} event{facilityEvents.length === 1 ? "" : "s"} in current window</p></div></div>{facilityEvents.length === 0 ? <p className="mt-8 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No facility-linked events are available for this time window.</p> : <div className="mt-8 space-y-5">{facilityEvents.map((event) => <div key={event.event_id}><div className="mb-2 flex justify-between gap-4 text-xs"><span className="font-semibold text-slate-700">{humanize(event.classification)}</span><span className="text-slate-500">Peak {event.max_frp?.toFixed(1) ?? "—"} MW · baseline {event.baseline_frp?.toFixed(1) ?? "—"} MW</span></div><div className="relative h-8 overflow-hidden rounded-lg bg-slate-100"><div className="absolute inset-y-0 left-0 bg-orange-500" style={{ width: `${((event.max_frp ?? 0) / max) * 100}%` }} /><div className="absolute inset-y-0 w-1 bg-slate-800" style={{ left: `${((event.baseline_frp ?? 0) / max) * 100}%` }} title="Baseline FRP" /></div></div>)}</div>}<p className="mt-6 text-xs text-slate-500">Orange bars show actual peak FRP; dark markers show the facility-specific baseline. Values come from the existing event API.</p></>}</section></div></section></main>;
}
