import type { AlertDetail } from "./alertTypes";

export function FrpBarChart({ data }: { data: AlertDetail["frp_series"] }) {
  const values = data.points.map((point) => point.frp).concat(data.baseline ?? 0);
  const max = Math.max(...values, 1);
  return <div className="h-64 rounded-xl border border-border bg-card p-4"><p className="text-sm font-semibold">FRP incident snapshot</p><p className="text-xs text-muted-foreground">Recent observations against facility baseline</p><svg viewBox="0 0 420 180" className="mt-3 h-44 w-full" role="img" aria-label="FRP bar chart">{data.points.map((point, index) => { const width = 48; const x = 24 + index * 68; const height = (point.frp / max) * 120; return <g key={`${point.timestamp}-${index}`}><rect x={x} y={150 - height} width={width} height={height} rx="4" className={point.current ? "fill-danger" : "fill-amber"} /><text x={x + 24} y="168" textAnchor="middle" className="fill-muted-foreground text-[9px]">{index + 1}</text></g>; })}{data.baseline != null && <><line x1="18" x2="400" y1={150 - (data.baseline / max) * 120} y2={150 - (data.baseline / max) * 120} className="stroke-info" strokeDasharray="5 4" /><text x="400" y={145 - (data.baseline / max) * 120} textAnchor="end" className="fill-info text-[9px]">baseline</text></>}</svg><div className="flex gap-4 text-xs text-muted-foreground"><span><i className="mr-1 inline-block h-2 w-2 rounded-sm bg-amber" />Earlier</span><span><i className="mr-1 inline-block h-2 w-2 rounded-sm bg-danger" />Current</span></div></div>;
}

export function ProbabilityChart({ probabilities }: { probabilities: Record<string, number> }) {
  const entries = Object.entries(probabilities); let cursor = 0; const colors = [["fill-danger", "bg-danger"], ["fill-amber", "bg-amber"], ["fill-info", "bg-info"], ["fill-muted-foreground", "bg-muted-foreground"]];
  const slices = entries.map(([label, value], index) => { const portion = Math.max(0, value); const start = cursor; cursor += portion; const large = portion > .5 ? 1 : 0; const a = (start * 360 - 90) * Math.PI / 180; const b = (cursor * 360 - 90) * Math.PI / 180; const d = `M 100 100 L ${100 + 72 * Math.cos(a)} ${100 + 72 * Math.sin(a)} A 72 72 0 ${large} 1 ${100 + 72 * Math.cos(b)} ${100 + 72 * Math.sin(b)} Z`; const [fillClass, dotClass] = colors[index % colors.length]; return { label, value, d, fillClass, dotClass }; });
  return <div className="h-64 rounded-xl border border-border bg-card p-4"><p className="text-sm font-semibold">Classification confidence</p><p className="text-xs text-muted-foreground">Probability breakdown</p><div className="flex items-center gap-3"><svg viewBox="0 0 200 200" className="h-40 w-40 shrink-0" role="img" aria-label="Classification probability pie chart">{slices.map((slice) => <path key={slice.label} d={slice.d} className={slice.fillClass} stroke="white" strokeWidth="2" />)}<circle cx="100" cy="100" r="38" className="fill-card" /></svg><div className="min-w-0 space-y-1 text-xs">{slices.map((slice) => <div key={slice.label} className="flex items-center gap-2"><i className={`h-2.5 w-2.5 rounded-full ${slice.dotClass}`} /><span className="truncate">{slice.label}</span><span className="ml-auto font-medium">{Math.round(slice.value * 100)}%</span></div>)}</div></div></div>;
}

export function PlumeImpactHero({ latitude, longitude, windDirection, population, facility }: { latitude: number; longitude: number; windDirection?: number | null; population?: number | null; facility: string }) {
  const direction = windDirection ?? 0;
  return <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-950 text-slate-100"><div className="grid gap-6 p-5 lg:grid-cols-[1.35fr_.65fr]"><div><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold tracking-[.2em] text-orange-300">FIRE SPREAD & PLUME</p><h2 className="mt-1 text-lg font-semibold">Modelled downwind impact corridor</h2></div><span className="rounded-full bg-orange-500/15 px-3 py-1 text-xs text-orange-200">Wind {Math.round(direction)}°</span></div><div className="relative mt-4 h-64 overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><svg viewBox="0 0 600 300" className="relative h-full w-full" role="img" aria-label="Event location and wind-aligned plume spread"><defs><pattern id="plume-grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M 32 0 L 0 0 0 32" className="fill-none stroke-slate-700" strokeWidth="1" /></pattern><marker id="arrowhead" markerWidth="9" markerHeight="9" refX="7" refY="4.5" orient="auto"><path d="M0,0 L9,4.5 L0,9 Z" className="fill-orange-300" /></marker></defs><rect width="600" height="300" fill="url(#plume-grid)" /><g transform={`rotate(${direction}, 300, 150)`}><path d="M300 150 L545 62 Q585 150 545 238 Z" className="fill-orange-500/25 stroke-orange-300" strokeWidth="2" /><path d="M300 150 L520 150" className="stroke-orange-300" strokeWidth="4" markerEnd="url(#arrowhead)" /><circle cx="300" cy="150" r="15" className="fill-danger stroke-orange-100" strokeWidth="4" /></g></svg><div className="absolute bottom-3 left-3 rounded bg-slate-950/90 px-3 py-2 text-xs"><span className="mr-2">🔥</span>Event source</div><div className="absolute right-3 top-3 rounded bg-slate-950/90 px-3 py-2 text-xs text-slate-300">Qualitative wind-aligned plume</div></div><p className="mt-3 text-xs leading-5 text-slate-400">Event at {latitude.toFixed(4)}, {longitude.toFixed(4)}. The cone shows the likely downwind corridor, not a dispersion forecast.</p></div><aside className="grid content-center gap-3"><div className="rounded-xl bg-slate-900 p-4"><p className="text-xs text-slate-400">Potentially exposed</p><p className="mt-1 text-3xl font-bold">~{Math.round(population ?? 0).toLocaleString()}</p><p className="text-xs text-slate-400">people in the impact context</p></div><div className="rounded-xl bg-slate-900 p-4"><p className="text-xs text-slate-400">Nearby asset context</p><p className="mt-1 font-semibold">{facility}</p><p className="mt-1 text-xs text-slate-400">Prioritize confirmation downwind.</p></div><div className="rounded-xl border border-orange-400/30 bg-orange-400/10 p-4"><p className="text-xs font-semibold text-orange-200">Recommended next step</p><p className="mt-1 text-sm text-orange-50">Verify source and check the downwind corridor before resolution.</p></div></aside></div></section>;
}

export function RiskImpactChart({ risk, population }: { risk: number; population?: number | null }) {
  const impact = Math.min(100, Math.log10((population ?? 0) + 1) * 25);
  return <div className="rounded-xl border border-border bg-card p-4"><p className="text-sm font-semibold">Risk × impact</p><p className="text-xs text-muted-foreground">Investigation priority signal</p><div className="mt-4 flex items-center gap-4"><svg viewBox="0 0 180 120" className="h-28 w-44" role="img" aria-label="Risk and impact comparison"><rect x="24" y="10" width="48" height="90" rx="4" className="fill-muted" /><rect x="108" y="10" width="48" height="90" rx="4" className="fill-muted" /><rect x="24" y={100 - Math.min(100, risk) * .9} width="48" height={Math.min(100, risk) * .9} rx="4" className="fill-danger" /><rect x="108" y={100 - impact * .9} width="48" height={impact * .9} rx="4" className="fill-amber" /><text x="48" y="116" textAnchor="middle" className="fill-muted-foreground text-[10px]">Risk</text><text x="132" y="116" textAnchor="middle" className="fill-muted-foreground text-[10px]">Impact</text></svg><p className="text-sm text-muted-foreground">Higher combined bars mean faster confirmation is warranted.</p></div></div>;
}
