import type { AlertDetail } from "./alertTypes";

export function FrpBarChart({ data }: { data: AlertDetail["frp_series"] }) {
  const values = data.points.map((point) => point.frp).concat(data.baseline ?? 0);
  const max = Math.max(...values, 1);
  return <div className="h-64 rounded-xl border border-border bg-card p-4"><p className="text-sm font-semibold">FRP incident snapshot</p><p className="text-xs text-muted-foreground">Recent observations against facility baseline</p><svg viewBox="0 0 420 180" className="mt-3 h-44 w-full" role="img" aria-label="FRP bar chart">{data.points.map((point, index) => { const width = 48; const x = 24 + index * 68; const height = (point.frp / max) * 120; return <g key={`${point.timestamp}-${index}`}><rect x={x} y={150 - height} width={width} height={height} rx="4" className={point.current ? "fill-danger" : "fill-amber"} /><text x={x + 24} y="168" textAnchor="middle" className="fill-muted-foreground text-[9px]">{index + 1}</text></g>; })}{data.baseline != null && <><line x1="18" x2="400" y1={150 - (data.baseline / max) * 120} y2={150 - (data.baseline / max) * 120} className="stroke-info" strokeDasharray="5 4" /><text x="400" y={145 - (data.baseline / max) * 120} textAnchor="end" className="fill-info text-[9px]">baseline</text></>}</svg><div className="flex gap-4 text-xs text-muted-foreground"><span><i className="mr-1 inline-block h-2 w-2 rounded-sm bg-amber" />Earlier</span><span><i className="mr-1 inline-block h-2 w-2 rounded-sm bg-danger" />Current</span></div></div>;
}

export function ProbabilityChart({ probabilities }: { probabilities: Record<string, number> }) {
  const entries = Object.entries(probabilities); let cursor = 0; const colors = [["fill-danger", "bg-danger"], ["fill-amber", "bg-amber"], ["fill-info", "bg-info"], ["fill-muted-foreground", "bg-muted-foreground"]];
  const slices = entries.map(([label, value], index) => { const portion = Math.max(0, value); const start = cursor; cursor += portion; const large = portion > .5 ? 1 : 0; const a = (start * 360 - 90) * Math.PI / 180; const b = (cursor * 360 - 90) * Math.PI / 180; const d = `M 100 100 L ${100 + 72 * Math.cos(a)} ${100 + 72 * Math.sin(a)} A 72 72 0 ${large} 1 ${100 + 72 * Math.cos(b)} ${100 + 72 * Math.sin(b)} Z`; const [fillClass, dotClass] = colors[index % colors.length]; return { label, value, d, fillClass, dotClass }; });
  return <div className="h-64 rounded-xl border border-border bg-card p-4"><p className="text-sm font-semibold">Classification confidence</p><p className="text-xs text-muted-foreground">Probability breakdown</p><div className="flex items-center gap-3"><svg viewBox="0 0 200 200" className="h-40 w-40 shrink-0" role="img" aria-label="Classification probability pie chart">{slices.map((slice) => <path key={slice.label} d={slice.d} className={slice.fillClass} stroke="white" strokeWidth="2" />)}<circle cx="100" cy="100" r="38" className="fill-card" /></svg><div className="min-w-0 space-y-1 text-xs">{slices.map((slice) => <div key={slice.label} className="flex items-center gap-2"><i className={`h-2.5 w-2.5 rounded-full ${slice.dotClass}`} /><span className="truncate">{slice.label}</span><span className="ml-auto font-medium">{Math.round(slice.value * 100)}%</span></div>)}</div></div></div>;
}
