import { Building2, ChevronRight, Flame, MapPinned } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";

import Navbar from "../../components/layout/Navbar";
import { humanize, severityTone, type Facility } from "../../types/thermal";

const API_BASE_URL = "http://127.0.0.1:8000";

export default function FacilitiesPage() {
  const { regionId = "dahej", facilityId } = useParams();
  const [facilities, setFacilities] = useState<Facility[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${API_BASE_URL}/facilities`).then((response) => response.json()).then((data) => setFacilities(data.facilities ?? [])).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => facilities.filter((facility) => `${facility.name} ${facility.facility_type ?? ""}`.toLowerCase().includes(query.toLowerCase())), [facilities, query]);
  const selected = facilities.find((facility) => facility.facility_id === facilityId);

  return <main className="min-h-screen bg-background text-foreground"><Navbar showRegionNav regionName={regionId.toUpperCase()} /><section className="mx-auto max-w-6xl px-4 py-6 md:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[0.16em] text-primary">FACILITY INTELLIGENCE</p><h1 className="mt-2 text-2xl font-bold">Industrial facilities</h1><p className="mt-1 text-sm text-muted-foreground">Behavioral baselines, incident history and environmental context.</p></div><Link to={`/region/${regionId}/explore`} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-bold text-slate-700 hover:bg-slate-50"><MapPinned className="h-4 w-4" />Explore map</Link></div><div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border p-4"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search facility or type" className="h-10 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-slate-500" /></div><div className="max-h-[560px] overflow-y-auto">{loading ? <p className="p-5 text-sm text-muted-foreground">Loading facilities...</p> : visible.map((facility) => <Link key={facility.facility_id} to={`/region/${regionId}/facilities/${facility.facility_id}`} className={`flex items-center gap-3 border-b border-slate-100 px-4 py-4 hover:bg-slate-50 ${selected?.facility_id === facility.facility_id ? "bg-orange-50" : ""}`}><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-600"><Building2 className="h-4 w-4" /></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-slate-800">{facility.name}</strong><span className="text-xs text-slate-500">{humanize(facility.facility_type)}</span></span><ChevronRight className="h-4 w-4 text-slate-400" /></Link>)}</div></section><FacilityProfile facility={selected} regionId={regionId} /></div></section></main>;
}

function FacilityProfile({ facility, regionId }: { facility: Facility | undefined; regionId: string }) {
  if (!facility) return <section className="grid min-h-[300px] place-items-center rounded-2xl border border-dashed border-slate-300 bg-card p-8 text-center"><div><Building2 className="mx-auto h-8 w-8 text-slate-300" /><h2 className="mt-3 font-bold text-slate-700">Select a facility</h2><p className="mt-1 max-w-sm text-sm text-slate-500">Choose a facility to inspect its current risk, incident record and environmental indicators.</p></div></section>;
  const riskLabel = facility.current_risk == null ? "Not available" : facility.current_risk >= 70 ? "High" : facility.current_risk >= 40 ? "Watch" : "Normal";
  return <section className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-[10px] font-bold tracking-[0.16em] text-primary">FACILITY PROFILE</p><h2 className="mt-1 text-xl font-bold">{facility.name}</h2><p className="mt-1 text-sm text-slate-500">{humanize(facility.facility_type)}{facility.operator ? ` · ${facility.operator}` : ""}</p></div><span className={`h-fit rounded-full px-3 py-1.5 text-xs font-bold uppercase ring-1 ${severityTone(riskLabel)}`}>{riskLabel} risk</span></div><div className="mt-6 grid grid-cols-2 gap-3"><FacilityMetric label="Historical events" value={String(facility.historical_event_count ?? "Not available")} /><FacilityMetric label="Anomalous events" value={String(facility.anomalous_event_count ?? "Not available")} /><FacilityMetric label="Cumulative emissions" value={facility.cumulative_emissions == null ? "Not available" : facility.cumulative_emissions.toFixed(1)} /><FacilityMetric label="Last incident" value={facility.last_incident ? new Date(facility.last_incident).toLocaleDateString("en-IN") : "Not available"} /></div><div className="mt-6 rounded-xl bg-slate-50 p-4"><div className="flex items-center gap-2"><Flame className="h-4 w-4 text-orange-500" /><h3 className="text-sm font-bold text-slate-800">History and compliance outlet</h3></div><p className="mt-2 text-sm leading-6 text-slate-600">This shared profile is ready for the baseline, incident timeline and compliance-chart modules. It uses the canonical facility identifier so each feature can attach without adding another route.</p></div><div className="mt-5 flex gap-4"><Link to={`/region/${regionId}/explore`} className="inline-flex items-center gap-2 text-sm font-bold text-orange-600 hover:text-orange-700"><MapPinned className="h-4 w-4" />View on map</Link><Link to={`/region/${regionId}/charts/${facility.facility_id}`} className="text-sm font-bold text-slate-700 hover:text-slate-950">Open chart view</Link></div></section>;
}
function FacilityMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-bold text-slate-800">{value}</p></div>; }
